"""
Comprehensive indicator configuration for Outcome Canada.
All 27 indicators with real Statistics Canada data.
"""

# Category display order and colors
CATEGORIES = {
    "Economic Growth": {"color": "#1a5276", "order": 1},
    "Labour Market": {"color": "#7d3c98", "order": 2},
    "Prices & Inflation": {"color": "#c0392b", "order": 3},
    "Housing": {"color": "#d68910", "order": 4},
    "Trade & Business": {"color": "#117864", "order": 5},
    "Financial": {"color": "#6c3483", "order": 6},
    "Demographics": {"color": "#1e8449", "order": 7},
}

INDICATORS = {
    # ===== ECONOMIC GROWTH =====
    "gdp": {
        "name": "Real GDP Growth",
        "category": "Economic Growth",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "36-10-0434-01",
        "value_col": "growth_yoy",
        "secondary_col": "growth_mom",
        "secondary_label": "M/M",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "Real GDP measures total economic output. Growth indicates economic expansion; contraction signals recession.",
        "methodology": "GDP data from Statistics Canada Table 36-10-0434-01 tracks real economic output across all industries. Monthly estimates provide timely insight into economic trends.",
    },
    "gdp_percapita": {
        "name": "GDP per Capita",
        "category": "Economic Growth",
        "unit": "C$ (2017)",
        "frequency": "Quarterly",
        "source": "Statistics Canada",
        "table": "36-10-0706-01",
        "value_col": "value",
        "secondary_col": "growth_yoy",
        "secondary_label": "Y/Y Growth",
        "secondary_unit": "%",
        "period_col": "target_quarter",
        "description": "GDP per capita measures economic output per person, a key indicator of living standards.",
        "methodology": "Sourced from Statistics Canada Table 36-10-0706-01. Real GDP divided by total population in chained 2017 dollars.",
    },

    # ===== LABOUR MARKET =====
    "unemployment": {
        "name": "Unemployment Rate",
        "category": "Labour Market",
        "unit": "%",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "14-10-0287-01",
        "value_col": "rate",
        "secondary_col": "yoy_change",
        "secondary_label": "Y/Y Change",
        "secondary_unit": "pp",
        "period_col": "target_month",
        "description": "The unemployment rate measures the share of the labour force actively seeking work but currently unemployed.",
        "methodology": "From Statistics Canada's Labour Force Survey (Table 14-10-0287-01), surveying 56,000 households monthly. Released first Friday after reference period.",
    },
    "employment_rate": {
        "name": "Employment Rate",
        "category": "Labour Market",
        "unit": "%",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "14-10-0287-01",
        "value_col": "rate",
        "secondary_col": "yoy_change",
        "secondary_label": "Y/Y Change",
        "secondary_unit": "pp",
        "period_col": "target_month",
        "description": "Employment rate shows the percentage of working-age population currently employed.",
        "methodology": "Labour Force Survey Table 14-10-0287-01. Employed persons as a percentage of population aged 15+.",
    },
    "participation_rate": {
        "name": "Participation Rate",
        "category": "Labour Market",
        "unit": "%",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "14-10-0287-01",
        "value_col": "rate",
        "secondary_col": "yoy_change",
        "secondary_label": "Y/Y Change",
        "secondary_unit": "pp",
        "period_col": "target_month",
        "description": "Participation rate measures the share of working-age population in the labour force (employed or seeking work).",
        "methodology": "Labour Force Survey Table 14-10-0287-01. Labour force as percentage of population 15 years and over.",
    },
    "wages": {
        "name": "Average Weekly Earnings",
        "category": "Labour Market",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "14-10-0222-01",
        "value_col": "wage_yoy",
        "secondary_col": "wage_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "Average weekly earnings track wage growth across all industries. Rising wages signal tight labour markets.",
        "methodology": "Survey of Employment, Payrolls and Hours (SEPH) Table 14-10-0222-01. Includes overtime for all employees. Released 60 days after reference period.",
    },
    "hours_worked": {
        "name": "Average Weekly Hours",
        "category": "Labour Market",
        "unit": "hours",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "14-10-0222-01",
        "value_col": "hours",
        "secondary_col": "monthly_change",
        "secondary_label": "Monthly Change",
        "secondary_unit": "hours",
        "period_col": "target_month",
        "description": "Average weekly hours worked indicates labour utilization and can signal economic shifts before employment changes.",
        "methodology": "SEPH Table 14-10-0222-01. Average hours including overtime for hourly employees across all industries.",
    },
    "ei": {
        "name": "EI Beneficiaries",
        "category": "Labour Market",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "14-10-0011-01",
        "value_col": "ei_yoy",
        "secondary_col": "ei_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "EI beneficiaries receiving regular benefits. Rising claims signal labour market stress and job losses.",
        "methodology": "Table 14-10-0011-01 counts Canadians receiving regular EI benefits. Released 45 days after reference period.",
    },
    "jobvacancy": {
        "name": "Job Vacancy Rate",
        "category": "Labour Market",
        "unit": "%",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "14-10-0372-01",
        "value_col": "vacancy_rate",
        "secondary_col": "vacancy_change",
        "secondary_label": "Monthly Change",
        "secondary_unit": "pp",
        "period_col": "target_month",
        "description": "Job vacancy rate measures unfilled positions as share of total labour demand, indicating labour market tightness.",
        "methodology": "Job Vacancy and Wage Survey Table 14-10-0372-01. Vacant positions / (employed + vacant) positions.",
    },

    # ===== PRICES & INFLATION =====
    "inflation": {
        "name": "CPI All-Items",
        "category": "Prices & Inflation",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "18-10-0004-01",
        "value_col": "inflation_yoy",
        "secondary_col": "inflation_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "Consumer Price Index measures the cost of a basket of goods and services. Bank of Canada targets 2% inflation.",
        "methodology": "Table 18-10-0004-01 tracks price changes for consumer goods including food, shelter, transportation, clothing. Released 3 weeks after reference period.",
    },
    "cpi_shelter": {
        "name": "CPI Shelter",
        "category": "Prices & Inflation",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "18-10-0004-01",
        "value_col": "inflation_yoy",
        "secondary_col": "inflation_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "CPI Shelter component tracks housing costs including rent, mortgage interest, utilities, and property taxes.",
        "methodology": "Shelter component from Table 18-10-0004-01. Major driver of overall inflation given housing's large weight in CPI basket.",
    },
    "cpi_food": {
        "name": "CPI Food",
        "category": "Prices & Inflation",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "18-10-0004-01",
        "value_col": "inflation_yoy",
        "secondary_col": "inflation_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "CPI Food component tracks grocery and restaurant food prices, a necessities affecting all households.",
        "methodology": "Food component from Table 18-10-0004-01 includes food purchased from stores and restaurants.",
    },
    "cpi_transport": {
        "name": "CPI Transportation",
        "category": "Prices & Inflation",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "18-10-0004-01",
        "value_col": "inflation_yoy",
        "secondary_col": "inflation_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "CPI Transportation tracks costs of vehicles, gasoline, insurance, and public transit.",
        "methodology": "Transportation component from Table 18-10-0004-01. Highly sensitive to energy prices and global oil markets.",
    },

    # ===== HOUSING =====
    "housing": {
        "name": "New Housing Price Index",
        "category": "Housing",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "18-10-0205-01",
        "value_col": "hpi_yoy",
        "secondary_col": "hpi_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "New Housing Price Index tracks selling prices of new residential houses, reflecting builder pricing and market conditions.",
        "methodology": "Table 18-10-0205-01 measures new home prices from contractors. Released 10 days after reference period.",
    },
    "housing_starts": {
        "name": "Housing Starts",
        "category": "Housing",
        "unit": "thousands (SAAR)",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "34-10-0158-01",
        "value_col": "starts",
        "secondary_col": "monthly_change",
        "secondary_label": "Monthly Change",
        "secondary_unit": "thousands",
        "period_col": "target_month",
        "description": "Housing starts measure new residential construction, a leading indicator of housing supply and economic activity.",
        "methodology": "CMHC Table 34-10-0158-01. Seasonally adjusted at annual rates (SAAR) for all dwelling types.",
    },

    # ===== TRADE & BUSINESS =====
    "trade": {
        "name": "Trade Balance",
        "category": "Trade & Business",
        "unit": "C$ millions",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "12-10-0011-01",
        "value_col": "balance_millions",
        "secondary_col": "monthly_change",
        "secondary_label": "Monthly Change",
        "secondary_unit": "C$ millions",
        "period_col": "target_month",
        "description": "Merchandise trade balance (exports minus imports). Positive = surplus; negative = deficit.",
        "methodology": "Table 12-10-0011-01 tracks international merchandise trade. Released 5 weeks after reference period.",
    },
    "exports": {
        "name": "Merchandise Exports",
        "category": "Trade & Business",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "12-10-0011-01",
        "value_col": "exports_yoy",
        "secondary_col": "exports_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "Total value of goods exported from Canada, a key driver of economic growth.",
        "methodology": "Export component from Table 12-10-0011-01. Balance of payments basis, seasonally adjusted.",
    },
    "imports": {
        "name": "Merchandise Imports",
        "category": "Trade & Business",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "12-10-0011-01",
        "value_col": "imports_yoy",
        "secondary_col": "imports_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "Total value of goods imported to Canada, reflecting domestic demand and competitiveness.",
        "methodology": "Import component from Table 12-10-0011-01. Balance of payments basis, seasonally adjusted.",
    },
    "retail": {
        "name": "Retail Sales",
        "category": "Trade & Business",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "20-10-0056-02",
        "value_col": "retail_yoy",
        "secondary_col": "retail_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "Retail trade measures consumer spending at stores, a key indicator of economic demand.",
        "methodology": "Monthly Retail Trade Survey Table 20-10-0056-02. Covers food, clothing, gasoline, general merchandise. Released 50 days after reference period.",
    },
    "manufacturing": {
        "name": "Manufacturing Sales",
        "category": "Trade & Business",
        "unit": "% y/y",
        "frequency": "Monthly",
        "source": "Statistics Canada",
        "table": "16-10-0047-01",
        "value_col": "mfg_yoy",
        "secondary_col": "mfg_annualized",
        "secondary_label": "Annualized",
        "secondary_unit": "%",
        "period_col": "target_month",
        "description": "Manufacturing sales (shipments) measure industrial production and goods demand.",
        "methodology": "Monthly Survey of Manufacturing Table 16-10-0047-01. Shipments from food, chemicals, machinery, vehicles. Released 50 days after reference period.",
    },
    "business_investment": {
        "name": "Business Investment",
        "category": "Trade & Business",
        "unit": "% y/y",
        "frequency": "Quarterly",
        "source": "Statistics Canada",
        "table": "36-10-0108-01",
        "value_col": "investment_yoy",
        "secondary_col": "investment_qoq",
        "secondary_label": "Q/Q",
        "secondary_unit": "%",
        "period_col": "target_quarter",
        "description": "Business non-residential investment in structures and equipment, a driver of productivity and growth.",
        "methodology": "Table 36-10-0108-01 tracks business gross fixed capital formation. Chained 2017 dollars, seasonally adjusted.",
    },

    # ===== FINANCIAL =====
    "policy_rate": {
        "name": "BoC Policy Rate",
        "category": "Financial",
        "unit": "%",
        "frequency": "Daily",
        "source": "Bank of Canada",
        "table": "10-10-0139-01",
        "value_col": "rate",
        "secondary_col": "change",
        "secondary_label": "Recent Change",
        "secondary_unit": "pp",
        "period_col": "target_date",
        "description": "Bank of Canada's target for the overnight rate, the primary tool for monetary policy.",
        "methodology": "Table 10-10-0139-01. Policy rate influences borrowing costs, inflation, and economic growth.",
    },
    "bond_5y": {
        "name": "5-Year Bond Yield",
        "category": "Financial",
        "unit": "%",
        "frequency": "Daily",
        "source": "Bank of Canada",
        "table": "10-10-0139-01",
        "value_col": "yield",
        "secondary_col": "change",
        "secondary_label": "Recent Change",
        "secondary_unit": "pp",
        "period_col": "target_date",
        "description": "5-year government bond yield, a benchmark for mortgage rates and medium-term borrowing costs.",
        "methodology": "Table 10-10-0139-01. Government of Canada benchmark bond yields reflect market expectations.",
    },
    "bond_10y": {
        "name": "10-Year Bond Yield",
        "category": "Financial",
        "unit": "%",
        "frequency": "Daily",
        "source": "Bank of Canada",
        "table": "10-10-0139-01",
        "value_col": "yield",
        "secondary_col": "change",
        "secondary_label": "Recent Change",
        "secondary_unit": "pp",
        "period_col": "target_date",
        "description": "10-year government bond yield, a key benchmark for long-term interest rates and economic expectations.",
        "methodology": "Table 10-10-0139-01. Long-term yield reflects inflation expectations and growth outlook.",
    },

    # ===== DEMOGRAPHICS =====
    "population": {
        "name": "Total Population",
        "category": "Demographics",
        "unit": "% y/y",
        "frequency": "Quarterly",
        "source": "Statistics Canada",
        "table": "17-10-0009-01",
        "value_col": "pop_yoy",
        "secondary_col": "pop_qoq",
        "secondary_label": "Q/Q",
        "secondary_unit": "%",
        "period_col": "target_quarter",
        "description": "Total population growth from births, deaths, and net migration. Fundamental for labour force and economic planning.",
        "methodology": "Table 17-10-0009-01 provides quarterly population estimates. Released 90 days after reference period.",
    },
    "immigration": {
        "name": "Immigrants",
        "category": "Demographics",
        "unit": "% y/y",
        "frequency": "Quarterly",
        "source": "Statistics Canada",
        "table": "17-10-0040-01",
        "value_col": "imm_yoy",
        "secondary_col": "imm_qoq",
        "secondary_label": "Q/Q",
        "secondary_unit": "%",
        "period_col": "target_quarter",
        "description": "Immigrant arrivals per quarter. Immigration is the largest component of Canada's population growth.",
        "methodology": "Table 17-10-0040-01 tracks permanent residents landing in Canada. Includes economic, family, refugee categories. Released 120 days after reference period.",
    },
    "emigration": {
        "name": "Emigrants",
        "category": "Demographics",
        "unit": "% y/y",
        "frequency": "Quarterly",
        "source": "Statistics Canada",
        "table": "17-10-0040-01",
        "value_col": "emig_yoy",
        "secondary_col": "emig_qoq",
        "secondary_label": "Q/Q",
        "secondary_unit": "%",
        "period_col": "target_quarter",
        "description": "Emigrants leaving Canada per quarter, a component of net migration.",
        "methodology": "Table 17-10-0040-01. Emigration estimates based on administrative data and census linkage.",
    },
}
