"""
Ministers scorecard configuration for Outcome Canada.
26 cabinet ministers, 78 trackable metrics.
"""

MINISTERS = {
    "carney": {
        "name": "Mark Carney",
        "title": "Prime Minister of Canada",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-08/Carney-200.jpg",
        "metrics": [
            {
                "key": "pm_gdp_growth",
                "name": "Real GDP (level)",
                "source": "Statistics Canada",
                "table": "36-10-0434-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "% y/y",
                "description": "Real GDP measures total economic output. Growth indicates expansion; contraction signals recession.",
            },
            {
                "key": "pm_gdp_percapita",
                "name": "Real GDP per Capita",
                "source": "Statistics Canada",
                "table": "36-10-0706-01",
                "frequency": "Quarterly",
                "rating": "HIGH",
                "unit": "C$ (2017)",
                "description": "GDP per capita measures economic output per person, a key indicator of living standards.",
            },
            {
                "key": "pm_unemployment",
                "name": "Unemployment Rate",
                "source": "Statistics Canada",
                "table": "14-10-0287-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "National unemployment rate from the Labour Force Survey, the most visible measure of labour market health.",
            },
            {
                "key": "pm_wages",
                "name": "Average Weekly Earnings",
                "source": "Statistics Canada",
                "table": "14-10-0223-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "% y/y",
                "description": "Year-over-year growth in average weekly earnings, measuring whether wages are keeping up with the cost of living.",
            },
            {
                "key": "pm_cpi",
                "name": "CPI Inflation",
                "source": "Statistics Canada",
                "table": "18-10-0004-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "% y/y",
                "description": "Consumer Price Index tracks the cost of a basket of goods and services. Bank of Canada targets 2%.",
            },
            {
                "key": "pm_retail",
                "name": "Retail Sales",
                "source": "Statistics Canada",
                "table": "20-10-0056-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "% y/y",
                "description": "Year-over-year growth in retail trade, a proxy for consumer confidence and household spending.",
            },
            {
                "key": "pm_employment",
                "name": "Employment Rate",
                "source": "Statistics Canada",
                "table": "14-10-0287-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Share of the working-age population that is employed, capturing discouraged workers that unemployment misses.",
            },
            {
                "key": "pm_trade",
                "name": "Trade Balance",
                "source": "Statistics Canada",
                "table": "12-10-0011-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "C$ millions",
                "description": "Merchandise trade balance (exports minus imports), measuring Canada's international economic position.",
            },
        ],
    },
    "leblanc": {
        "name": "Dominic LeBlanc",
        "title": "Canada\u2013U.S. Trade / Intergovernmental / Internal Trade",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/LeBlanc-2026.jpg",
        "metrics": [
            {
                "key": "leblanc_exports_us",
                "name": "Merchandise Exports to the U.S.",
                "source": "Statistics Canada",
                "table": "12-10-0011-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Value of Canadian merchandise exports to the United States, our largest trading partner.",
            },
            {
                "key": "leblanc_diversification",
                "name": "Export Diversification (% Non-U.S.)",
                "source": "Statistics Canada",
                "table": "12-10-0011-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Share of Canadian exports going to non-U.S. markets, measuring trade diversification progress.",
                "latest": {
                    "value": "31.7%",
                    "detail": "\u2191 2.2 pp year over year",
                    "detail_color": "positive",
                    "period": "2025-11",
                },
            },
            {
                "key": "leblanc_cfta",
                "name": "Interprovincial Trade Flows",
                "source": "Statistics Canada",
                "table": "36-10-0222-01",
                "frequency": "Annual",
                "rating": "MODERATE",
                "unit": "C$ billions",
                "description": "Total value of goods and services traded across provincial and territorial borders, from the GDP expenditure accounts.",
                "latest": {
                    "value": "$527B",
                    "detail": "\u2191 2.3% year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
        ],
    },
    "joly": {
        "name": "M\u00e9lanie Joly",
        "title": "Industry",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/Joly-2026.jpg",
        "metrics": [
            {
                "key": "joly_productivity",
                "name": "Labour Productivity in Business",
                "source": "Statistics Canada",
                "table": "36-10-0480-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ per hour",
                "description": "Real GDP per hour worked across the business sector, a key driver of long-term prosperity.",
                "latest": {
                    "value": "$59.2/hr",
                    "detail": "\u2191 0.2% year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "joly_investment",
                "name": "Business Gross Fixed Capital Formation",
                "source": "Statistics Canada",
                "table": "36-10-0104-01",
                "frequency": "Quarterly",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Total business gross fixed capital formation (real, SAAR, chained 2017$), measuring investment in productive capacity.",
            },
            {
                "key": "joly_manufacturing",
                "name": "Manufacturing Sales Growth",
                "source": "Statistics Canada",
                "table": "16-10-0047-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "% y/y",
                "description": "Year-over-year growth in manufacturing shipments, a direct measure of industrial output and goods demand.",
            },
        ],
    },
    "champagne": {
        "name": "Fran\u00e7ois-Philippe Champagne",
        "title": "Finance and National Revenue",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-08/Champagne_200x200_V2.jpg",
        "metrics": [
            {
                "key": "champagne_debt",
                "name": "Federal Debt-to-GDP",
                "source": "Finance Canada https://www.canada.ca/en/department-finance/services/publications/fiscal-reference-tables/2025/part-1.html",
                "table": "Fiscal Reference Tables",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "% of GDP",
                "description": "Federal debt (accumulated deficit) as share of GDP, the primary measure of fiscal sustainability.",
                "latest": {
                    "value": "41.2%",
                    "detail": "\u2193 0.9 pp year over year",
                    "detail_color": "positive",
                    "period": "2024/25",
                },
            },
            {
                "key": "champagne_balance",
                "name": "Budget Balance / Deficit-to-GDP",
                "source": "Finance Canada https://www.canada.ca/en/department-finance/services/publications/annual-financial-report/2025.html",
                "table": "Annual Financial Report",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "% of GDP",
                "description": "Federal budgetary balance as share of GDP. Negative indicates deficit; positive indicates surplus.",
                "latest": {
                    "value": "-1.2%",
                    "detail": "\u2191 0.9 pp year over year",
                    "detail_color": "positive",
                    "period": "2024/25",
                },
            },
            {
                "key": "champagne_revenue",
                "name": "Federal Tax Revenue",
                "source": "Finance Canada https://www.canada.ca/en/department-finance/services/publications/fiscal-monitor/2025/09.html",
                "table": "Fiscal Monitor",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Cumulative federal tax revenues (income tax, GST, customs duties) from the monthly Fiscal Monitor.",
                "latest": {
                    "value": "$198.2B",
                    "detail": "\u2191 5.4% year over year",
                    "detail_color": "positive",
                    "period": "Apr-Sep 2025/26",
                },
            },
        ],
    },
    "anand": {
        "name": "Anita Anand",
        "title": "Foreign Affairs",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-02/Anand.jpg",
        "metrics": [
            {
                "key": "anand_services_exports",
                "name": "Exports of Services (BoP)",
                "source": "Statistics Canada https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210015701",
                "table": "12-10-0157-01",
                "frequency": "Quarterly",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Canada's international services exports (balance of payments basis), a proxy for economic diplomacy and engagement.",
                "latest": {
                    "value": "$59.8B",
                    "detail": "\u2191 1.8% quarter over quarter",
                    "detail_color": "positive",
                    "period": "2025-Q3",
                },
            },
            {
                "key": "anand_cdia",
                "name": "Canadian Direct Investment Abroad",
                "source": "Statistics Canada https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610000801",
                "table": "36-10-0008-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ trillions",
                "description": "Total book value of Canadian direct investment abroad, measuring global economic engagement.",
                "latest": {
                    "value": "$2.47T",
                    "detail": "\u2191 12.0% year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "anand_fdi",
                "name": "Foreign Direct Investment in Canada",
                "source": "Statistics Canada https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610000801",
                "table": "36-10-0008-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ trillions",
                "description": "Total book value of foreign direct investment in Canada, measuring international investor confidence and economic engagement.",
                "latest": {
                    "value": "$1.50T",
                    "detail": "\u2191 5.5% year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
        ],
    },
    "hajdu": {
        "name": "Patty Hajdu",
        "title": "Jobs and Families",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/Hajdu-2026.jpg",
        "metrics": [
            {
                "key": "hajdu_employment",
                "name": "Employment Rate (Core-Age 25\u201354)",
                "source": "Statistics Canada",
                "table": "14-10-0287-02",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Employment rate for core working-age adults (25-54), the key measure of labour market health.",
                "latest": {
                    "value": "83.3%",
                    "detail": "\u2193 0.3 pp year over year",
                    "detail_color": "negative",
                    "period": "2026-01",
                },
            },
            {
                "key": "hajdu_income",
                "name": "Median Family Income (After-Tax)",
                "source": "Statistics Canada",
                "table": "11-10-0190-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$",
                "description": "Median after-tax income for economic families in Canada (2023 constant dollars), a direct measure of family financial wellbeing.",
                "latest": {
                    "value": "$104,800",
                    "detail": "\u2191 1.1% year over year",
                    "detail_color": "positive",
                    "period": "2023",
                },
            },
            {
                "key": "hajdu_youth",
                "name": "Youth Employment Rate (15\u201324)",
                "source": "Statistics Canada",
                "table": "14-10-0287-02",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Employment rate for youth aged 15-24, measuring young Canadians' ability to find work.",
                "latest": {
                    "value": "54.6%",
                    "detail": "\u2191 0.2 pp year over year",
                    "detail_color": "positive",
                    "period": "2026-01",
                },
            },
        ],
    },
    "miller": {
        "name": "Marc Miller",
        "title": "Canadian Identity and Culture / Official Languages",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-12/Miller_200x200_V2.jpg",
        "metrics": [
            {
                "key": "miller_immersion",
                "name": "French Immersion Enrollment",
                "source": "Statistics Canada",
                "table": "37-10-0009-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "students",
                "description": "Number of students enrolled in French immersion and second-language programs in public schools.",
                "latest": {
                    "value": "477,105",
                    "detail": "\u2191 0.6% year over year",
                    "detail_color": "positive",
                    "period": "2023/24",
                },
            },
            {
                "key": "miller_culture_gdp",
                "name": "Arts & Recreation GDP (NAICS 71)",
                "source": "Statistics Canada",
                "table": "36-10-0434-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "GDP of the arts, entertainment, and recreation sector (NAICS 71) from monthly GDP by industry. Chained 2017 dollars, SAAR.",
                "latest": {
                    "value": "$19.1B",
                    "detail": "\u2191 0.2% year over year",
                    "detail_color": "positive",
                    "period": "2025-11",
                },
            },
            {
                "key": "miller_culture_employment",
                "name": "Information, Culture & Recreation Employment",
                "source": "Statistics Canada",
                "table": "14-10-0355-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "jobs",
                "description": "Employment in information, culture, and recreation (NAICS 51, 71) from the monthly Labour Force Survey.",
                "latest": {
                    "value": "882,300",
                    "detail": "\u2191 3.6% year over year",
                    "detail_color": "positive",
                    "period": "2026-01",
                },
            },
        ],
    },
    "fraser": {
        "name": "Sean Fraser",
        "title": "Justice and Attorney General",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2023-07/Fraser_200x200_2.jpg",
        "metrics": [
            {
                "key": "fraser_disposition",
                "name": "Median Time to Disposition",
                "source": "Statistics Canada",
                "table": "35-10-0029-01",
                "frequency": "Annual",
                "rating": "MODERATE",
                "unit": "days",
                "description": "Median elapsed time from first to last court appearance for completed criminal cases.",
                "latest": {
                    "value": "189",
                    "detail": "\u2193 6.0% year over year",
                    "detail_color": "positive",
                    "period": "2023/24",
                },
            },
            {
                "key": "fraser_jordan",
                "name": "Cases Exceeding 1 Year",
                "source": "Statistics Canada",
                "table": "35-10-0028-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of completed criminal cases with elapsed time exceeding one year, a proxy for cases at risk of exceeding Jordan ceilings.",
                "latest": {
                    "value": "25.7%",
                    "detail": "\u2193 2.5 pp year over year",
                    "detail_color": "positive",
                    "period": "2023/24",
                },
            },
        ],
    },
    "anandasangaree": {
        "name": "Gary Anandasangaree",
        "title": "Public Safety",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/Anandasangaree-2026.jpg",
        "metrics": [
            {
                "key": "anandasangaree_homicides",
                "name": "Homicides",
                "source": "Statistics Canada",
                "table": "35-10-0068-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "victims",
                "description": "Total number of homicide victims in Canada reported by police.",
                "latest": {
                    "value": "788",
                    "detail": "\u2193 1.0% year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "anandasangaree_autotheft",
                "name": "Motor Vehicle Thefts",
                "source": "Statistics Canada",
                "table": "35-10-0177-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "incidents",
                "description": "Total police-reported motor vehicle theft incidents in Canada.",
                "latest": {
                    "value": "98,779",
                    "detail": "\u2193 14.2% year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "anandasangaree_opioid",
                "name": "Opioid Overdose Deaths",
                "source": "Government of Canada https://www.canada.ca/en/privy-council/services/publications/canada-fentanyl-czar-interim-report-june-2025.html",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "deaths",
                "description": "Total apparent opioid toxicity deaths in Canada, tracking the overdose crisis. Note: 2024 national totals include BC (all unregulated drugs) and Quebec (drug/opioid-related intoxication) under revised definitions.",
                "latest": {
                    "value": "7,146",
                    "detail": "\u2193 17.0% year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "anandasangaree_hatecrimes",
                "name": "Police-Reported Hate Crimes",
                "source": "Statistics Canada",
                "table": "35-10-0191-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "incidents",
                "description": "Total police-reported hate crime incidents in Canada.",
            },
        ],
    },
    "valdez": {
        "name": "Rechie Valdez",
        "title": "Women and Gender Equality; Small Business & Tourism",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-09/Valdez.jpg",
        "metrics": [
            {
                "key": "valdez_wagegap",
                "name": "Gender Wage Gap",
                "source": "Statistics Canada",
                "table": "14-10-0417-02",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Median hourly wage gap between men and women, measuring progress toward pay equity.",
                "latest": {
                    "value": "12.6%",
                    "detail": "\u2191 0.1 pp year over year",
                    "detail_color": "negative",
                    "period": "2025",
                },
            },
            {
                "key": "valdez_female_unemployment",
                "name": "Female Unemployment Rate",
                "source": "Statistics Canada",
                "table": "14-10-0287-02",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Unemployment rate for women aged 15 and over, seasonally adjusted.",
                "latest": {
                    "value": "6.3%",
                    "detail": "\u2193 0.1 pp year over year",
                    "detail_color": "positive",
                    "period": "2026-01",
                },
            },
            {
                "key": "valdez_tourism",
                "name": "Tourism Spending in Canada",
                "source": "Statistics Canada",
                "table": "36-10-0230-01",
                "frequency": "Quarterly",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Total tourism spending in Canada (domestic + foreign) from the National Tourism Indicators. Chained 2017 dollars, seasonally adjusted.",
                "latest": {
                    "value": "$26.7B",
                    "detail": "\u2191 0.7% quarter over quarter",
                    "detail_color": "positive",
                    "period": "2025-Q3",
                },
            },
        ],
    },
    "mackinnon": {
        "name": "Steven MacKinnon",
        "title": "Transport",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/MacKinnon-2026.jpg",
        "metrics": [
            {
                "key": "mackinnon_rail",
                "name": "Rail Freight Traffic Volume",
                "source": "Statistics Canada",
                "table": "23-10-0216-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "million tonnes",
                "description": "Total rail traffic carried in Canada (carloading + intermodal + US connections), a key supply chain indicator.",
                "latest": {
                    "value": "31.4M t",
                    "detail": "\u2191 0.5% year over year",
                    "detail_color": "positive",
                    "period": "2025-11",
                },
            },
            {
                "key": "mackinnon_port",
                "name": "Air Passenger Traffic",
                "source": "Statistics Canada",
                "table": "23-10-0079-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "passengers",
                "description": "Monthly scheduled and charter passenger traffic on Canadian Level I air carriers.",
                "latest": {
                    "value": "6.5M",
                    "detail": "\u2193 0.3% year over year",
                    "detail_color": "negative",
                    "period": "2025-11",
                },
            },
            {
                "key": "mackinnon_safety",
                "name": "Transportation Safety (Fatalities)",
                "source": "TSB: Rail https://www.tsb.gc.ca/eng/stats/rail/2024/sser-ssro-2024.html (69), Air https://www.tsb.gc.ca/eng/stats/aviation/2024/ssea-ssao-2024.html (46), Marine https://www.tsb.gc.ca/eng/stats/marine/2024/ssem-ssmo-2024.html (12), Pipeline https://www.tsb.gc.ca/eng/stats/pipeline/2024/ssep-sspo-2024.html (0)",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "fatalities",
                "description": "Total fatalities across federally regulated transportation modes (rail, air, marine, pipeline) from TSB annual occurrence statistics.",
                "latest": {
                    "value": "127",
                    "detail": "\u2191 7.6% year over year",
                    "detail_color": "negative",
                    "period": "2024",
                },
            },
        ],
    },
    "mcguinty": {
        "name": "David J. McGuinty",
        "title": "National Defence",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/McGuinty-2026_1.jpg",
        "metrics": [
            {
                "key": "mcguinty_spending",
                "name": "Defence Spending as % of GDP",
                "source": "DND https://www.canada.ca/en/department-national-defence/news/2025/06/canadas-new-government-is-rebuilding-rearming-and-reinvesting-in-the-canadian-armed-forces.html",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "MODERATE",
                "unit": "% of GDP",
                "description": "Canadian defence expenditure as share of GDP. NATO guideline target is 2%. FY 2023-24 comparator: 1.31%.",
                "latest": {
                    "value": "1.37%",
                    "detail": "\u2191 0.06 pp year over year",
                    "detail_color": "positive",
                    "period": "2024/25",
                },
            },
            {
                "key": "mcguinty_staffing",
                "name": "CAF Regular Force Strength",
                "source": "DND https://search.open.canada.ca/qpnotes/record/dnd-mdn,DND-2025-QP-000010",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "MODERATE-HIGH",
                "unit": "personnel",
                "description": "Canadian Armed Forces Regular Force personnel strength as of fiscal year-end (March 31).",
                "latest": {
                    "value": "65,700",
                    "detail": "as of March 31, 2025",
                    "detail_color": "neutral",
                    "period": "2024/25",
                },
            },
            {
                "key": "mcguinty_strength",
                "name": "CAF Strength vs Target (71,500)",
                "source": "DND https://www.canada.ca/en/department-national-defence/corporate/policies-standards/dm-cds-directives/directive-002-reconstitution.html",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "MODERATE-HIGH",
                "unit": "% of authorized",
                "description": "CAF Regular Force strength as percentage of authorized target of 71,500. Based on 65,700 Regular Force as of March 31, 2025.",
                "latest": {
                    "value": "92%",
                    "detail": "~5,800 below target",
                    "detail_color": "negative",
                    "period": "2024/25",
                },
            },
        ],
    },
    "thompson": {
        "name": "Joanne Thompson",
        "title": "Fisheries",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-09/joanne-thompson-200x200.jpg",
        "metrics": [
            {
                "key": "thompson_stocks",
                "name": "Fish Stocks in Healthy Zone",
                "source": "DFO Sustainability Survey https://www.dfo-mpo.gc.ca/reports-rapports/regs/sff-cpd/survey-sondage/comparison-comparaison-en.html",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "MODERATE",
                "unit": "%",
                "description": "Percentage of major fish stocks assessed as being in the healthy zone (72 of 198 stocks in 2024).",
                "latest": {
                    "value": "36%",
                    "detail": "\u2191 1.2 pp year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "thompson_landed",
                "name": "Landed Value of Commercial Fisheries",
                "source": "DFO Commercial Fisheries Landings https://www.dfo-mpo.gc.ca/stats/commercial/land-debarq/sea-maritimes/s2024pv-eng.htm",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Total landed value of sea fisheries across Canada (Atlantic and Pacific coasts).",
                "latest": {
                    "value": "$4.0B",
                    "detail": "\u2191 11.1% year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "thompson_exports",
                "name": "Fisheries Export Value",
                "source": "DFO Trade Data https://inter-j02.dfo-mpo.gc.ca/ctr/canadiantrade?lang=en",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Value of Canadian fish and seafood exports.",
                "latest": {
                    "value": "$7.9B",
                    "detail": "\u2193 2.9% year over year",
                    "detail_color": "negative",
                    "period": "2025",
                },
            },
        ],
    },
    "ali": {
        "name": "Shafqat Ali",
        "title": "Treasury Board",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/Ali-2026.jpg",
        "metrics": [
            {
                "key": "ali_standards",
                "name": "Services Meeting Standards",
                "source": "TBS Departmental Results Report https://www.canada.ca/en/treasury-board-secretariat/corporate/reports/treasury-board-canada-secretariat-2024-25-departmental-results-report.html",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "MODERATE",
                "unit": "%",
                "description": "In 2024-25, 52% of high-volume Government of Canada services (45,000+ transactions/year) met their published service standards (target: 80%), down from 55% in 2023-24. Reporting shifted from priority to high-volume services under the Policy on Service and Digital. Across all services, individual service standards were met 73% of the time.",
                "latest": {
                    "value": "52%",
                    "detail": "\u2193 3.0 pp year over year",
                    "detail_color": "negative",
                    "period": "2024/25",
                },
            },
            {
                "key": "ali_headcount",
                "name": "Federal Public Servants per 1,000 Population",
                "source": "TBS https://www.canada.ca/en/treasury-board-secretariat/services/innovation/human-resources-statistics/population-federal-public-service.html",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "per 1,000",
                "description": "Federal public service headcount (357,965 as of March 31, 2025) divided by Canada's total population (41,604,555 from StatCan Table 17-10-0009-01), measuring the size of the federal workforce relative to the country. Prior year: 9.0 per 1,000 (367,772 / 40,990,297).",
                "latest": {
                    "value": "8.6",
                    "detail": "\u2193 4.1% year over year",
                    "detail_color": "positive",
                    "period": "March 2025",
                },
            },
            {
                "key": "ali_regulations",
                "name": "Administrative Burden Baseline (ABB)",
                "source": "TBS Annual Report https://www.canada.ca/en/treasury-board-secretariat/corporate/reports/annual-reports-parliament-federal-regulatory-management-initiatives/annual-report-2024-2025-fiscal-year-federal-regulatory-management-initiatives.html",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "requirements",
                "description": "Total administrative requirements (paperwork/information obligations) across 601 federal regulations reported by 38 regulators under the Administrative Burden Baseline. Count changes do not necessarily equal cost changes.",
                "latest": {
                    "value": "149,312",
                    "detail": "\u2193 89 year over year",
                    "detail_color": "positive",
                    "period": "June 2024",
                },
            },
        ],
    },
    "alty": {
        "name": "Rebecca Alty",
        "title": "Crown-Indigenous Relations",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-08/Alty_V2.jpg",
        "metrics": [
            {
                "key": "alty_selfgov",
                "name": "Treaties / Self-Government Agreements / Other Constructive Arrangements (Cumulative)",
                "source": "CIRNAC 2024-25 Departmental Results Report https://www.rcaanc-cirnac.gc.ca/eng/1757705818512/1757705860962",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "MODERATE",
                "unit": "agreements",
                "description": "Cumulative number of treaties, self-government agreements, and other constructive arrangements concluded with Indigenous nations.",
                "latest": {
                    "value": "94",
                    "detail": "\u2191 22.1% year over year",
                    "detail_color": "positive",
                    "period": "2024/25",
                },
            },
            {
                "key": "alty_codeveloped",
                "name": "Indigenous People with Co-Developed Agreements",
                "source": "CIRNAC 2024-25 Departmental Results Report https://www.rcaanc-cirnac.gc.ca/eng/1757705818512/1757705860962",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of Indigenous people that have reached preliminary types of co-developed agreements. Target is 90%.",
                "latest": {
                    "value": "90%",
                    "detail": "\u2191 19.0 pp year over year",
                    "detail_color": "positive",
                    "period": "2024/25",
                },
            },
        ],
    },
    "chartrand": {
        "name": "Rebecca Chartrand",
        "title": "Northern & Arctic Affairs",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/Chartrand-2026.jpg",
        "metrics": [
            {
                "key": "chartrand_food",
                "name": "Northern Food Price Index",
                "source": "Statistics Canada https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401",
                "table": "18-10-0004-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "% y/y",
                "description": "Average year-over-year change in food CPI in territorial capitals (Whitehorse +4.9%, Yellowknife +3.8%).",
                "latest": {
                    "value": "+4.3%",
                    "detail": "\u2191 4.3% year over year",
                    "detail_color": "negative",
                    "period": "2025-12",
                },
            },
            {
                "key": "chartrand_employment",
                "name": "Northern Employment Rate",
                "source": "Statistics Canada https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410029202",
                "table": "14-10-0292-02",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Combined employment rate across the three territories, computed as total employed / total population 15+ (Yukon, NWT, Nunavut). Three-month moving average, seasonally adjusted.",
                "latest": {
                    "value": "63.4%",
                    "detail": "\u2193 2.4 pp year over year",
                    "detail_color": "negative",
                    "period": "2026-01",
                },
            },
            {
                "key": "chartrand_population",
                "name": "Northern Population",
                "source": "Statistics Canada https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1710000901",
                "table": "17-10-0009-01",
                "frequency": "Quarterly",
                "rating": "HIGH",
                "unit": "persons",
                "description": "Combined population of the three territories (Yukon 48,261, NWT 45,848, Nunavut 41,919). Quarterly postcensal estimates.",
                "latest": {
                    "value": "136,028",
                    "detail": "\u2191 0.8% year over year",
                    "detail_color": "positive",
                    "period": "Q4 2025",
                },
            },
        ],
    },
    "dabrusin": {
        "name": "Julie Aviva Dabrusin",
        "title": "Environment, Climate Change and Nature",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-09/Dabrusin_V2.jpg",
        "metrics": [
            {
                "key": "dabrusin_ghg",
                "name": "National GHG Emissions",
                "source": "ECCC https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/greenhouse-gas-emissions.html",
                "table": "National Inventory Report",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "Mt CO\u2082e",
                "description": "Canada's total greenhouse gas emissions (National Inventory Report). 2030 target: 40\u201345% below 2005 levels (730 Mt).",
                "latest": {
                    "value": "694 Mt",
                    "detail": "\u2193 0.9% year over year",
                    "detail_color": "positive",
                    "period": "2023",
                },
            },
            {
                "key": "dabrusin_terrestrial",
                "name": "Terrestrial Area Conserved",
                "source": "ECCC https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/protected-conserved-areas.html",
                "table": "CPCAD",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of Canada's terrestrial area (land and inland water) recognized as conserved. Target: 30% by 2030.",
                "latest": {
                    "value": "13.8%",
                    "detail": "\u2191 0.2 pp year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "dabrusin_marine",
                "name": "Marine Area Conserved",
                "source": "ECCC https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/protected-conserved-areas.html",
                "table": "CPCAD",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of Canada's coastal and marine area recognized as conserved. Target: 30% by 2030.",
                "latest": {
                    "value": "15.5%",
                    "detail": "\u2191 1.2 pp year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
        ],
    },
    "diab": {
        "name": "Lena Metlege Diab",
        "title": "Immigration, Refugees and Citizenship",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/Diab-2026.jpg",
        "metrics": [
            {
                "key": "diab_backlog_ee",
                "name": "Backlog: Federal High-Skilled (Express Entry)",
                "source": "IRCC https://www.canada.ca/en/immigration-refugees-citizenship/corporate/reports-statistics/statistics-open-data/immigration-stats/application-inventory.html#federal-high-skilled-express-entry",
                "table": "N/A",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Share of Express Entry federal high-skilled applications outside service standards.",
                "latest": {
                    "value": "32%",
                    "detail": "\u2191 14 pp year over year",
                    "detail_color": "negative",
                    "period": "2025-11",
                },
            },
            {
                "key": "diab_backlog_pnp",
                "name": "Backlog: Provincial Nominee Program (Express Entry)",
                "source": "IRCC https://www.canada.ca/en/immigration-refugees-citizenship/corporate/reports-statistics/statistics-open-data/immigration-stats/application-inventory.html#provincial-nominee-program-express-entry",
                "table": "N/A",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Share of Express Entry-aligned PNP applications outside service standards.",
                "latest": {
                    "value": "53%",
                    "detail": "\u2191 29 pp year over year",
                    "detail_color": "negative",
                    "period": "2025-11",
                },
            },
            {
                "key": "diab_backlog_trv",
                "name": "Backlog: Temporary Resident Visas (TRV)",
                "source": "IRCC https://www.canada.ca/en/immigration-refugees-citizenship/corporate/reports-statistics/statistics-open-data/immigration-stats/application-inventory.html#temporary-resident-visas-trv",
                "table": "N/A",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Share of TRV applications outside service standards.",
                "latest": {
                    "value": "57%",
                    "detail": "\u2193 18 pp year over year",
                    "detail_color": "positive",
                    "period": "2025-11",
                },
            },
            {
                "key": "diab_backlog_study",
                "name": "Backlog: Study Permits (excl. Extensions)",
                "source": "IRCC https://www.canada.ca/en/immigration-refugees-citizenship/corporate/reports-statistics/statistics-open-data/immigration-stats/application-inventory.html#study-permits-excluding-extensions",
                "table": "N/A",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Share of study permit (new applications) outside service standards.",
                "latest": {
                    "value": "36%",
                    "detail": "\u2192 0 pp year over year",
                    "detail_color": "neutral",
                    "period": "2025-11",
                },
            },
            {
                "key": "diab_unemployment",
                "name": "Immigrant Unemployment Rate",
                "source": "Statistics Canada",
                "table": "14-10-0472-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Unemployment rate among immigrants in Canada, measuring labour market integration.",
                "latest": {
                    "value": "6.8%",
                    "detail": "",
                    "detail_color": "neutral",
                    "period": "2025",
                },
            },
        ],
    },
    "gullmasty": {
        "name": "Mandy Gull-Masty",
        "title": "Indigenous Services",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-05/Gull-Masty.jpg",
        "metrics": [
            {
                "key": "gullmasty_water",
                "name": "Long-Term Drinking Water Advisories",
                "source": "ISC https://www.sac-isc.gc.ca/eng/1614387410146/1614387435325",
                "table": "N/A",
                "frequency": "Point-in-time",
                "rating": "HIGH",
                "unit": "advisories",
                "description": "Number of active long-term drinking water advisories on public systems on reserve (and communities affected).",
                "latest": {
                    "value": "39",
                    "detail": "as of 2026-02-10",
                    "detail_color": "neutral",
                    "period": "2026-02-10",
                },
            },
            {
                "key": "gullmasty_jordan",
                "name": "Jordan's Principle Expenditures",
                "source": "ISC https://www.sac-isc.gc.ca/eng/1753100031042/1753100058429",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ millions",
                "description": "Total Jordan's Principle expenditures (Vote 1 O&M + Vote 10 G&C), as of March 31, 2024, including program administration O&M costs.",
                "latest": {
                    "value": "$1,699.4M",
                    "detail": "\u2191 74.5% vs FY 2022\u201323",
                    "detail_color": "positive",
                    "period": "2023/24",
                },
            },
        ],
    },
    "hodgson": {
        "name": "Tim Hodgson",
        "title": "Energy and Natural Resources",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/Hodgson-2026.jpg",
        "metrics": [
            {
                "key": "hodgson_investment",
                "name": "Capital Spending Intentions (Mining, Quarrying & Oil and Gas Extraction)",
                "source": "Statistics Canada https://www150.statcan.gc.ca/n1/daily-quotidien/250226/dq250226a-eng.htm",
                "table": "34-10-0035-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Capital and repair spending intentions for mining, quarrying, and oil and gas extraction (NAICS 21). 2025 figure is intentions surveyed Sep 2024\u2013Jan 2025, not realized investment.",
                "latest": {
                    "value": "$64.4B",
                    "detail": "\u2191 5.4% year over year",
                    "detail_color": "positive",
                    "period": "2025 (intentions)",
                },
            },
            {
                "key": "hodgson_utilities",
                "name": "Capital Spending Intentions (Utilities)",
                "source": "Statistics Canada https://www150.statcan.gc.ca/n1/daily-quotidien/250226/dq250226a-eng.htm",
                "table": "34-10-0035-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Capital and repair spending intentions for utilities (NAICS 22), including electric power generation, transmission, and distribution. 2025 figure is intentions surveyed Sep 2024\u2013Jan 2025.",
                "latest": {
                    "value": "$49.1B",
                    "detail": "\u2191 10.3% year over year",
                    "detail_color": "positive",
                    "period": "2025 (intentions)",
                },
            },
            {
                "key": "hodgson_clean",
                "name": "Proportion of Electricity from Renewable & Non-GHG Sources (%)",
                "source": "ECCC https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/greenhouse-gas-emissions.html",
                "table": "25-10-0015-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Proportion of electricity generated from renewable and other non-GHG emitting sources (%). FSDS indicator; derived from Statistics Canada Table 25-10-0015-01.",
                "latest": {
                    "value": "79.4%",
                    "detail": "\u2193 1.3 pp year over year",
                    "detail_color": "negative",
                    "period": "2024",
                },
            },
        ],
    },
    "lightbound": {
        "name": "Jo\u00ebl Lightbound",
        "title": "Government Transformation / Public Works & Procurement",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-12/Lightbound-Dec_2025_EN.jpg",
        "metrics": [
            {
                "key": "lightbound_procurement",
                "name": "PSPC Managed Procurement Value",
                "source": "PSPC https://www.canada.ca/en/public-services-procurement/corporate/transparency/departmental-results-report/2024-25.html",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Total value of goods and services PSPC managed procurement for on behalf of client departments and agencies.",
                "latest": {
                    "value": "$52B",
                    "detail": "\u2191 64.6% year over year",
                    "detail_color": "neutral",
                    "period": "2024/25",
                },
            },
            {
                "key": "lightbound_timeliness",
                "name": "Procurement Timeliness (Standard Complexity)",
                "source": "PSPC https://www.canada.ca/en/public-services-procurement/corporate/transparency/departmental-results-report/2024-25.html",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of original contracts of level 2 (Standard) complexity awarded within established timeframes.",
                "latest": {
                    "value": "64%",
                    "detail": "\u2193 2 pp year over year",
                    "detail_color": "negative",
                    "period": "2024/25",
                },
            },
            {
                "key": "lightbound_efficiency",
                "name": "Procurement Cost Efficiency",
                "source": "PSPC https://www.canada.ca/en/public-services-procurement/corporate/transparency/departmental-results-report/2024-25.html",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "$ per $100",
                "description": "Cost of procurement services per $100 of contract value (lower is better).",
                "latest": {
                    "value": "$0.93",
                    "detail": "\u2193 21.8% year over year",
                    "detail_color": "positive",
                    "period": "2024/25",
                },
            },
        ],
    },
    "macdonald": {
        "name": "Heath MacDonald",
        "title": "Agriculture and Agri-Food",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-05/MacDonald.jpg",
        "metrics": [
            {
                "key": "macdonald_exports",
                "name": "Agri-Food and Seafood Export Value",
                "source": "AAFC https://agriculture.canada.ca/en/department/transparency/departmental-results-report/agriculture-and-agri-food-canadas-2024-25-departmental-results-report",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Total value of Canadian agri-food and seafood exports (calendar year; AAFC Global Trade Tracker).",
                "latest": {
                    "value": "$100.3B",
                    "detail": "\u2191 1.1% year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "macdonald_income",
                "name": "Farm Net Income",
                "source": "Statistics Canada",
                "table": "32-10-0052-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Realized net farm income across all Canadian farms.",
                "latest": {
                    "value": "$9.2B",
                    "detail": "\u2193 31.3% year over year",
                    "detail_color": "negative",
                    "period": "2024",
                },
            },
            {
                "key": "macdonald_productivity",
                "name": "Farm Cash Receipts",
                "source": "Statistics Canada",
                "table": "32-10-0046-01",
                "frequency": "Quarterly",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Total farm cash receipts from crops, livestock, and direct payments, published quarterly.",
                "latest": {
                    "value": "$25.6B",
                    "detail": "\u2191 3.1% year over year",
                    "detail_color": "positive",
                    "period": "2025-Q1",
                },
            },
        ],
    },
    "mcknight": {
        "name": "Jill McKnight",
        "title": "Veterans Affairs",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/McKnight-2026.jpg",
        "metrics": [
            {
                "key": "mcknight_processing",
                "name": "Disability Benefit Processing Time",
                "source": "VAC https://search.open.canada.ca/qpnotes/record/vac-acc%2CVAC-2025-QP-00001",
                "table": "N/A",
                "frequency": "Fiscal YTD",
                "rating": "HIGH",
                "unit": "weeks",
                "description": "Average turnaround time to process disability benefit first applications. Service standard: 16 weeks.",
                "latest": {
                    "value": "23.9 weeks",
                    "detail": "\u2191 23.2% year over year",
                    "detail_color": "negative",
                    "period": "2025-09-30",
                },
            },
            {
                "key": "mcknight_backlog",
                "name": "Disability Benefit Backlog",
                "source": "VAC QP Note https://search.open.canada.ca/qpnotes/record/vac-acc%2CVAC-2025-QP-00001 (VAC-2025-QP-00001); YoY comparator: https://search.open.canada.ca/qpnotes/record/vac-acc%2CVAC-2023-QP-00055 (VAC-2023-QP-00055)",
                "table": "N/A",
                "frequency": "Quarterly",
                "rating": "HIGH",
                "unit": "applications",
                "description": "Number of disability benefit first applications over the 16-week service standard (quarter-end snapshot).",
                "latest": {
                    "value": "12,761",
                    "detail": "\u2191 104.3% year over year",
                    "detail_color": "negative",
                    "period": "2025-09-30",
                },
            },
            {
                "key": "mcknight_standard",
                "name": "% Meeting 16-Week Standard",
                "source": "VAC https://www.veterans.gc.ca/en/about-vac/reports-policies-and-legislation/departmental-reports/departmental-results-reports/departmental-results-report-2024-2025",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of disability benefit first applications decided within the 16-week service standard.",
                "latest": {
                    "value": "47%",
                    "detail": "\u2193 22.0 pp year over year",
                    "detail_color": "negative",
                    "period": "2024/25",
                },
            },
        ],
    },
    "michel": {
        "name": "Marjorie Michel",
        "title": "Health",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/Michel.jpg",
        "metrics": [
            {
                "key": "michel_hip",
                "name": "Hip Replacement Within Benchmark",
                "source": "CIHI https://www.cihi.ca/en/wait-times-for-priority-procedures-in-canada-2025",
                "table": "N/A",
                "frequency": "Semi-annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of hip replacements completed within the 26-week benchmark (Apr\u2013Sep reporting period).",
                "latest": {
                    "value": "67.9%",
                    "detail": "\u2191 2.4 pp year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "michel_knee",
                "name": "Knee Replacement Within Benchmark",
                "source": "CIHI https://www.cihi.ca/en/wait-times-for-priority-procedures-in-canada-2025",
                "table": "N/A",
                "frequency": "Semi-annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of knee replacements completed within the 26-week benchmark (Apr\u2013Sep reporting period).",
                "latest": {
                    "value": "61.4%",
                    "detail": "\u2191 2.5 pp year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "michel_cataract",
                "name": "Cataract Surgery Within Benchmark",
                "source": "CIHI https://www.cihi.ca/en/wait-times-for-priority-procedures-in-canada-2025",
                "table": "N/A",
                "frequency": "Semi-annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of cataract surgeries completed within the 112-day benchmark (Apr\u2013Sep reporting period).",
                "latest": {
                    "value": "69.0%",
                    "detail": "\u2193 0.6 pp year over year",
                    "detail_color": "negative",
                    "period": "2024",
                },
            },
            {
                "key": "michel_radiation",
                "name": "Radiation Therapy Within Benchmark",
                "source": "CIHI https://www.cihi.ca/en/wait-times-for-priority-procedures-in-canada-2025",
                "table": "N/A",
                "frequency": "Semi-annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of patients receiving radiation therapy within the 28-day benchmark (Apr\u2013Sep reporting period).",
                "latest": {
                    "value": "94.1%",
                    "detail": "\u2191 1.0 pp year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "michel_hipfracture",
                "name": "Hip Fracture Repair Within Benchmark",
                "source": "CIHI https://www.cihi.ca/en/wait-times-for-priority-procedures-in-canada-2025",
                "table": "N/A",
                "frequency": "Semi-annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "Percentage of hip fracture repairs completed within the 48-hour benchmark (Apr\u2013Sep reporting period).",
                "latest": {
                    "value": "83.1%",
                    "detail": "\u2191 2.1 pp year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
            {
                "key": "michel_overdose",
                "name": "Opioid Toxicity Death Rate",
                "source": "PHAC https://sdgcif-data-canada-oddcic-donnee.github.io/3-13-1/",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "per 100K",
                "description": "Crude rate of apparent opioid toxicity deaths per 100,000 population.",
                "latest": {
                    "value": "17.7",
                    "detail": "\u2193 11.5% year over year",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
        ],
    },
    "olszewski": {
        "name": "Eleanor Olszewski",
        "title": "Emergency Management and Community Resilience",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/Olszewski.jpg",
        "metrics": [
            {
                "key": "olszewski_losses",
                "name": "Catastrophic Insured Losses",
                "source": "IBC https://www.ibc.ca/news-insights/news/2024-shatters-record-for-costliest-year-for-severe-weather-related-losses-in-canadian-history-at-8-5-billion / CatIQ https://public.catiq.com/2025/01/13/canadian-insured-losses-from-catastrophic-events-total-can-8-5-billion-in-2024/",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Annual insured losses from catastrophic severe weather events in Canada.",
                "latest": {
                    "value": "$8.55B",
                    "detail": "\u2191 136.8% year over year",
                    "detail_color": "negative",
                    "period": "2024",
                },
            },
            {
                "key": "olszewski_events",
                "name": "Active DFAA Disaster Event Files",
                "source": "Public Safety financial statements FY ended Mar 31, 2024 (76 DFAA events): https://www.publicsafety.gc.ca/cnt/rsrcs/pblctns/dprtmntl-rslts-rprt-2023-24/fnncl-sttmnts-en.aspx Public Safety financial statements FY ended Mar 31, 2023 (68 DFAA events): https://www.publicsafety.gc.ca/cnt/rsrcs/pblctns/dprtmntl-rslts-rprt-2022-23/fnncl-sttmnts-en.aspx",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "events",
                "description": "Number of natural disaster events with federal cost-sharing agreed and final payments not yet made (DFAA financial statements, FY ended March 31, 2024).",
                "latest": {
                    "value": "76",
                    "detail": "\u2191 11.8% year over year",
                    "detail_color": "negative",
                    "period": "2024",
                },
            },
            {
                "key": "olszewski_mitigation",
                "name": "DMAF Funding Committed",
                "source": "Public Safety Canada https://www.publicsafety.gc.ca/cnt/trnsprnc/brfng-mtrls/prlmntry-bndrs/20240322/14-en.aspx / HICC https://www.canada.ca/en/housing-infrastructure-communities/news/2023/01/infrastructure-canada-accepting-applications-to-the-disaster-mitigation-and-adaptation-fund.html",
                "table": "N/A",
                "frequency": "Cumulative",
                "rating": "MODERATE",
                "unit": "C$ billions",
                "description": "Total federal DMAF funding envelope / cumulative commitment for resilience-building projects.",
                "latest": {
                    "value": "$3.8B",
                    "detail": "\u2191 11.8% vs Jan 2023 baseline",
                    "detail_color": "positive",
                    "period": "2024",
                },
            },
        ],
    },
    "robertson": {
        "name": "Gregor Robertson",
        "title": "Housing and Infrastructure",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2026-01/Robertson.jpg",
        "metrics": [
            {
                "key": "robertson_starts",
                "name": "Housing Starts (SAAR, all areas)",
                "source": "CMHC + Statistics Canada",
                "table": "34-10-0158-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "units (SAAR)",
                "description": "Seasonally adjusted annual rate of total housing starts (all areas), a high-frequency new-supply indicator.",
                "latest": {
                    "value": "282,439",
                    "detail": "\u2191 22.02% year over year",
                    "detail_color": "positive",
                    "period": "2025-12",
                },
            },
            {
                "key": "robertson_vacancy",
                "name": "Purpose-Built Rental Apartment Vacancy Rate (Canada)",
                "source": "CMHC https://www.cmhc-schl.gc.ca/professionals/housing-markets-data-and-research/market-reports/rental-market-reports-major-centres",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "%",
                "description": "National vacancy rate for purpose-built rental apartments, indicating rental market tightness/availability.",
                "latest": {
                    "value": "3.1%",
                    "detail": "\u2191 0.9 pp year over year",
                    "detail_color": "positive",
                    "period": "2025-10",
                },
            },
            {
                "key": "robertson_rent",
                "name": "Average 2-Bedroom Rent (Purpose-Built, Canada)",
                "source": "CMHC https://www.cmhc-schl.gc.ca/professionals/housing-markets-data-and-research/market-reports/rental-market-reports-major-centres",
                "table": "N/A",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "C$",
                "description": "Average rent for 2-bedroom purpose-built apartments (same-sample), capturing rent inflation pressures.",
                "latest": {
                    "value": "$1,550",
                    "detail": "\u2191 5.10% year over year",
                    "detail_color": "negative",
                    "period": "2025-10",
                },
            },
            {
                "key": "robertson_permits",
                "name": "Dwelling Units Authorized by Building Permits (Canada)",
                "source": "Statistics Canada https://www150.statcan.gc.ca/n1/daily-quotidien/260211/dq260211a-eng.htm",
                "table": "34-10-0292-01",
                "frequency": "Annual",
                "rating": "HIGH",
                "unit": "units",
                "description": "Total dwelling units authorized by building permits, a leading indicator of future housing supply.",
                "latest": {
                    "value": "308,600",
                    "detail": "\u2191 6.60% year over year",
                    "detail_color": "positive",
                    "period": "2025",
                },
            },
            {
                "key": "robertson_homelessness",
                "name": "Chronic Homelessness Rate (Median, per 10,000)",
                "source": "HICC https://housing-infrastructure.canada.ca/homelessness-sans-abri/reports-rapports/nat-homelessness-indic-07-2025-pancan-litinerance-eng.html",
                "table": "N/A",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "per 10K",
                "description": "Median chronic homelessness rate per 10,000 people (By-Name List), reported monthly by participating communities.",
                "latest": {
                    "value": "16.5",
                    "detail": "\u2191 25.95% year over year",
                    "detail_color": "negative",
                    "period": "2025-10",
                },
            },
        ],
    },
    "sidhu": {
        "name": "Maninder Sidhu",
        "title": "International Trade",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-12/Sidhu-2.jpg",
        "metrics": [
            {
                "key": "sidhu_exports",
                "name": "Real Exports Growth",
                "source": "Statistics Canada https://www150.statcan.gc.ca/n1/daily-quotidien/251128/dq251128a-eng.htm ; https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010401",
                "table": "36-10-0104-01",
                "frequency": "Quarterly",
                "rating": "HIGH",
                "unit": "% q/q",
                "description": "Quarter-over-quarter growth in real exports of goods and services (chained 2017 dollars), from GDP expenditure accounts.",
                "latest": {
                    "value": "+0.2%",
                    "detail": "rebound from \u22127.0% in Q2 2025",
                    "detail_color": "positive",
                    "period": "2025-Q3",
                },
            },
            {
                "key": "sidhu_diversification",
                "name": "Export Diversification (% Non-U.S.)",
                "source": "Statistics Canada https://www150.statcan.gc.ca/n1/daily-quotidien/260129/t001a-eng.htm ; https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1210001101",
                "table": "12-10-0011-01",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Share of Canadian merchandise exports going to non-U.S. markets (calculated as (Total exports \u2212 Exports to U.S.) / Total exports; Nov 2025 total=63,943; U.S.=43,669; Nov 2024 share=23.7%).",
                "latest": {
                    "value": "31.7%",
                    "detail": "\u2191 8.0 pp year over year",
                    "detail_color": "positive",
                    "period": "2025-11",
                },
            },
            {
                "key": "sidhu_fdi",
                "name": "FDI Inflows",
                "source": "Statistics Canada https://www150.statcan.gc.ca/n1/daily-quotidien/251127/dq251127a-eng.htm ; https://www150.statcan.gc.ca/n1/daily-quotidien/241128/dq241128a-eng.htm ; https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610047201",
                "table": "36-10-0472-01",
                "frequency": "Quarterly",
                "rating": "HIGH",
                "unit": "C$ billions",
                "description": "Foreign direct investment in Canada (Q3 2025 = $18.2B vs Q3 2024 = $27.1B, YoY % change computed from StatCan Daily values).",
                "latest": {
                    "value": "$18.2B",
                    "detail": "\u2193 32.8% year over year",
                    "detail_color": "negative",
                    "period": "2025-Q3",
                },
            },
        ],
    },
    "solomon": {
        "name": "Evan Solomon",
        "title": "Artificial Intelligence and Digital Innovation",
        "photo": "https://www.pm.gc.ca/sites/pm/files/styles/portrait_square/public/media/minister/2025-10/Solomon_en.jpg",
        "metrics": [
            {
                "key": "solomon_ai",
                "name": "Business AI Adoption Rate",
                "source": "Statistics Canada https://www150.statcan.gc.ca/n1/pub/11-621-m/11-621-m2025008-eng.htm",
                "table": "CSBC (11-621-M2025008)",
                "frequency": "Quarterly",
                "rating": "HIGH",
                "unit": "%",
                "description": "Share of businesses using AI to produce goods or deliver services.",
                "latest": {
                    "value": "12.2%",
                    "detail": "\u2191 6.1 pp year over year",
                    "detail_color": "positive",
                    "period": "2025-Q2",
                },
            },
            {
                "key": "solomon_ict_employment",
                "name": "ICT Sector Employment (proxy: NAICS 54 only)",
                "source": "Statistics Canada https://www150.statcan.gc.ca/n1/daily-quotidien/250207/dq250207a-eng.htm",
                "table": "LFS \u2014 The Daily",
                "frequency": "Monthly",
                "rating": "HIGH",
                "unit": "jobs",
                "description": "Employment in professional, scientific and technical services (NAICS 54); level derived from the Daily's reported YoY change (+66,000; +3.4%).",
                "latest": {
                    "value": "2.01M",
                    "detail": "\u2191 3.4% year over year",
                    "detail_color": "positive",
                    "period": "2025-01",
                },
            },
            {
                "key": "solomon_vc",
                "name": "Venture Capital Investment (YTD through Q3)",
                "source": "CVCA https://www.cvca.ca/insights/market-reports/q3-2025/",
                "table": "N/A",
                "frequency": "Quarterly",
                "rating": "MODERATE-HIGH",
                "unit": "C$ billions",
                "description": "Total Canadian VC investment (YTD + Q3).",
                "latest": {
                    "value": "$4.9B; Q3: $1.8B",
                    "detail": "\u2191 7% quarter over quarter",
                    "detail_color": "positive",
                    "period": "2025-Q3",
                },
            },
        ],
    },
}
